[package]
name = "ofllm"
version = "0.2.0"
edition = "2021"
description = "GL4 - Fastest float parser in Rust, 1.28ms per 1M rows"
license = "BSL-1.1"
repository = "https://github.com/Hovo80/OfLLM"
authors = ["Hovhannes Martirosyan <Hovo80@github>"]
readme = "README.md"
keywords = ["csv", "parser", "simd", "float", "performance"]
categories = ["parsing", "performance"]

[dependencies]